name: ripples
version: "2"
summary: Ripples game
description: Make ripples by touching and clicking
confinement: strict
base: core18

apps:
  run:
    command: bin/ripples
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio/"
    adapter: full
    plugs:
     - opengl
     - wayland

parts:
  wrapper:
    plugin: dump
    source: wrapper
    organize:  
      run.sh: bin/ripples.wrapper
  ripples:
    plugin: cmake
    source: src/
    build-packages:
      - build-essential
      - cmake
      - g++
      - libgles2-mesa-dev
      - pkg-config
      - libsdl2-dev
      - libsdl2-gfx-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-gfx-1.0-0
      - libdri2-1
      - libdrm2
      - libgles2-mesa
      - libgl1-mesa-glx
      - libpulse0
environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/arm-linux-gnueabihf/:$SNAP/usr/lib/arm-linux-gnueabihf/dri:$SNAP/usr/lib/arm-linux-gnueabihf/mesa:$SNAP/usr/lib/arm-linux-gnueabihf/mesa-gl:$SNAP/usr/lib/arm-linux-gnueabihf/xorg:$SNAP/usr/lib/arm-linux-gnueabihf/pulseaudio/
