name: ripples
version: "1"
summary: Ripples game
description: Make ripples by touching and clicking
confinement: strict

apps:
  ripples:
    daemon: simple
    command: ripples.wrapper
    plugs:
     - opengl
     - wayland

parts:
  wrapper:
    plugin: dump
    source: wrapper
    organize:  
      run.sh: bin/ripples.wrapper
  ripples:
    plugin: cmake
    source: https://github.com/knitzsche/ripples
    source-type: git
    build-packages:
      - build-essential
      - cmake
      - g++
      - libgles2-mesa-dev
      - pkg-config
      - libsdl2-dev
      - libsdl2-gfx-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-gfx-1.0-0
      - libdri2-1
      - libdrm2
      - libgles2-mesa
      - libgl1-mesa-glx
      - libpulse0
environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/arm-linux-gnueabihf/:$SNAP/usr/lib/arm-linux-gnueabihf/dri:$SNAP/usr/lib/arm-linux-gnueabihf/mesa:$SNAP/usr/lib/arm-linux-gnueabihf/mesa-gl:$SNAP/usr/lib/arm-linux-gnueabihf/xorg:$SNAP/usr/lib/arm-linux-gnueabihf/pulseaudio/
