name: ripples 
version: "0.1"
summary: Ripples game
description: Make ripples by touching and clicking
confinement: devmode 

apps:
  run:
    command: bin/ripples

parts:
  learnit:
    plugin: cmake
    source: https://github.com/knitzsche/ripples
    source-type: git      
    snap:
      - bin/ripples
    build-packages:
      - build-essential
      - cmake
      - g++
      - libgles2-mesa-dev
      - pkg-config
      - libsdl2-dev
      - libsdl2-gfx-dev
    stage-pacakges:
      - libsdl2
      - libsdl2-gfx
  environment:
    plugin: copy
    files:
      - ripples.wrapper: bin/ripples
